[package]
name = "dra"
version = "0.4.6"
edition = "2021"
authors = ["Cosimo Matteini <dev.matteini@gmail.com>"]
description = "A command line tool to download release assets from GitHub"
homepage = "https://github.com/devmatteini/dra"
repository = "https://github.com/devmatteini/dra"
documentation = "https://github.com/devmatteini/dra"
readme = "README.md"
license = "MIT"
categories = ["command-line-utilities"]
keywords = ["github", "cli"]

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1

[dependencies]
ureq = { version = "2.6.2", default-features = false, features = ["tls", "json"] }
serde = { version = "1.0.159", features = ["derive"] }
clap = { version = "4.1.11", features = ["derive"] }
clap_complete = "4.1.5"
dialoguer = "0.10.3"
indicatif = "0.17.3"
uuid = { version = "1.3.0", features = ["v4"] }
ctrlc = "3.2.5"
walkdir = "2.3.3"
zip = { version = "0.6.4", default-features = false, features = ["deflate"] }
flate2 = { version = "1.0.25", features = ["zlib"] }
tar = "0.4.38"
xz2 = "0.1.7"
bzip2 = "0.4.4"

[dev-dependencies]
test-case = "2.2.2"
assert_cmd = "2.0.5"
predicates = "2.1.5"

[package.metadata.deb]
section = "utility"
extended-description = """\
Download Release Assets (dra) is a command line tool
to download release assets from GitHub.
Provides interactive and non-interactive ways to download assets
to meet your needs in different scenarios.
"""
