[package]
name = "dra"
version = "0.3.2"
edition = "2021"
authors = ["Cosimo Matteini <dev.matteini@gmail.com>"]
description = "A command line tool to download release assets from GitHub"
homepage = "https://github.com/devmatteini/dra"
repository = "https://github.com/devmatteini/dra"
documentation = "https://github.com/devmatteini/dra"
readme = "README.md"
license = "MIT"
categories = ["command-line-utilities"]
keywords = ["github", "cli"]

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1

[dependencies]
ureq = { version = "2.4.0", default-features = false, features = ["tls", "json"] }
serde = { version = "1.0.136", features = ["derive"] }
clap = { version = "3.1.8", features = ["derive"] }
clap_complete = "3.1.1"
dialoguer = "0.9.0"
indicatif = "0.16.2"
uuid = { version = "0.8.2", features = ["v4"] }
ctrlc = "3.2.1"

[dev-dependencies]
test-case = "1.2.1"
predicates = "2.1.1"

[package.metadata.deb]
section = "utility"
extended-description = """\
Download Release Assets (dra) is a command line tool
to download release assets from GitHub.
Provides interactive and non-interactive ways to download assets
to meet your needs in different scenarios.
"""
