[package]
name = "dra"
version = "0.3.8"
edition = "2021"
authors = ["Cosimo Matteini <dev.matteini@gmail.com>"]
description = "A command line tool to download release assets from GitHub"
homepage = "https://github.com/devmatteini/dra"
repository = "https://github.com/devmatteini/dra"
documentation = "https://github.com/devmatteini/dra"
readme = "README.md"
license = "MIT"
categories = ["command-line-utilities"]
keywords = ["github", "cli"]

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1

[dependencies]
ureq = { version = "2.5.0", default-features = false, features = ["tls", "json"] }
serde = { version = "1.0.145", features = ["derive"] }
clap = { version = "4.0", features = ["derive"] }
clap_complete = "4.0"
dialoguer = "0.10.2"
indicatif = "0.17.1"
uuid = { version = "1.2.1", features = ["v4"] }
ctrlc = "3.2.2"
walkdir = "2.3.2"

[dev-dependencies]
test-case = "2.2.2"

[package.metadata.deb]
section = "utility"
extended-description = """\
Download Release Assets (dra) is a command line tool
to download release assets from GitHub.
Provides interactive and non-interactive ways to download assets
to meet your needs in different scenarios.
"""
